# .github/workflows/main.yml
name: Deploy Node App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy using SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/ubuntu/services/wtfMusic
            git fetch origin
            git checkout main
            git pull
            sudo docker build -t music-server .
            sudo docker stop music-server-container || true
            sudo docker rm music-server-container || true
            sudo docker run -d --name music-server-container -p 3000:6969 music-server
